[IG]
; 以下のig＝には、sushi が生成したImplementationGuide-eCheckupReport.jsonの所在（ローカルパス）を記述します。
ig = fsh-generated/resources/ImplementationGuide-eCheckupReport.json
template = #custom-template
css-includes = input/includes/custom.css
