# ╭─────────────────────────Commonly Used ImplementationGuide Properties───────────────────────────╮
# │  The properties below are used to create the ImplementationGuide resource. The most commonly   │
# │  used properties are included. For a list of all supported properties and their functions,     │
# │  see: https://fshschool.org/docs/sushi/configuration/.                                  │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯
id: eCheckupReport
canonical: http://jpfhir.jp/fhir/eCheckupReport
name: "健診結果報告FHIR記述仕様　実装ガイド"
title: "健診結果報告FHIR記述仕様　実装ガイド"
description: "健診結果報告FHIR記述仕様　実装ガイド eCheckupReport Implementation Guide"
status: active # draft | active | retired | unknown
version: 1.2.0
date: 2024-09-20
fhirVersion: 4.0.1 # https://www.hl7.org/fhir/valueset-FHIR-version.html 
copyrightYear: 2023+
releaseLabel: release # ci-build | draft | qa-preview | ballot | trial-use | release | update | normative+trial-use
# license: CC0-1.0 # https://www.hl7.org/fhir/valueset-spdx-license.html
# jurisdiction: urn:iso:std:iso:3166#US "United States of America" # https://www.hl7.org/fhir/valueset-jurisdiction.html
publisher:
  name: 管理団体：（一社）日本HL7協会、（一社）日本医療情報学会.
  url: http://jpfhir.jp
  email: office@hlfhir.jp
copyright:  （一社）日本HL7協会、（一社）日本医療情報学会.　CC(Creative Commons) BY-ND 4.0
jurisdiction: 'urn:iso:std:iso:3166-2#JP'
dependencies:
  jp-core.r4:
    uri: http://jpfhir.jp/fhir/core/1.1.2/ImplementationGuide/
    version: 1.1.2
  jpfhir-terminology.r4:
    uri: http://jpfhir.jp/fhir//jpfhir-terminology.r4/ImplementationGuide/
    version: 1.2.1


#----------------------------------------
# ページタイトル名称設定
#----------------------------------------
pages:
  index.md:
    title: 健診結果報告書HL7&reg; FHIR&reg;記述仕様第1.2版　実装ガイド
  validationGuide.md:
    title: Validationガイド
  history.md:
    title: 改訂履歴
#-------------------------------------
# メニュー設定
#-------------------------------------
menu:
  Home:
    本文: index.html
    プロファイル: artifacts.html
    改訂履歴: history.html
  Artifacts: 
    Artifacts: artifacts.html
  Validationガイド:
    Validationガイド: validationGuide.html
  パッケージDownload:
    標準(diff)版: https://jpfhir.jp/fhir/eCheckup/jp-eCheckupReport.r4-1.2.0.tgz 
    snapshot版: https://jpfhir.jp/fhir/eCheckup/jp-eCheckupReport.r4-1.2.0-snap.tgz
#-----------------------------------------
# IG 外部パラメータ設定
#-----------------------------------------
parameters:  # see https://confluence.hl7.org/display/FHIR/Implementation+Guide+Parameters
  path-resource:
    - input/resources
    - fsh-generated/resources
  path-pages:
    - input/pagecontent
    - input/intro-notes
    - fsh-generated/includes
    #- input/summaries
  path-expansion-params: '../../input/_resources/exp-params.json'
  no-narrative: 
    - CodeSystem/*
  active-tables: 'false'
  apply-version: 'false'
  apply-copyright: 'true'
  apply-publisher: 'true'
  apply-contact: 'true'
  apply-license: 'true'
  apply-jurisdiction: 'true'
  show-inherited-invariants: 'true'
  usage-stats-opt-out: 'true'
  display-warnings: 'true'
  excludexml: 'true'
  excludejson: 'false'
  excludettl: 'true'
  excludemap: 'true'
#  excludeexample: 'false'
  generate: #what does this do - todo: remove and see
    - json
  no-validate:
    - '*/hl7.fhir.jp.core'
  special-url:
    - http://jpfhir.jp/fhir/core/StructureDefinition/JP_Binary
    - http://jpfhir.jp/fhir/clins/StructureDefinition/JP_Bundle_eCheckupGeneral
    - http://jpfhir.jp/fhir/clins/StructureDefinition/JP_Bundle_eCheckupGeneral
    - http://jpfhir.jp/fhir/eCheckup/StructureDefinition/JP_Composition_eCheckupGeneral
    - http://jpfhir.jp/fhir/eCS/StructureDefinition/JP_Consent_eCS
    - http://jpfhir.jp/fhir/core/StructureDefinition/JP_Consent
    - http://jpfhir.jp/fhir/eCheckup/StructureDefinition/JP_CoverageInsurance_eCheckupGeneral
    - http://jpfhir.jp/fhir/eCheckup/StructureDefinition/JP_CoverageService_eCheckupGeneral
    - http://jpfhir.jp/fhir/eCS/StructureDefinition/JP_Device_eCS
    - http://jpfhir.jp/fhir/core/StructureDefinition/JP_Device
    - http://jpfhir.jp/fhir/eCS/StructureDefinition/JP_DeviceUseStatement_eCS
    - http://jpfhir.jp/fhir/core/StructureDefinition/JP_DeviceUseStatement
    - http://jpfhir.jp/fhir/eCheckup/StructureDefinition/JP_DiagnosticReport_eCheckupGeneral
    - http://jpfhir.jp/fhir/eCS/StructureDefinition/JP_DocumentReference_CDAdocument
    - http://jpfhir.jp/fhir/eCS/StructureDefinition/JP_DocumentReference_eCS
    - http://jpfhir.jp/fhir/eCheckup/StructureDefinition/JP_DocumentReference_eCheckupGeneral
    - http://jpfhir.jp/fhir/eCheckup/StructureDefinition/JP_Encounter_eCheckupGeneral
    - http://jpfhir.jp/fhir/eCS/StructureDefinition/JP_Immunization_eCS
    - http://jpfhir.jp/fhir/eCheckup/StructureDefinition/JP_Media_eCheckupGeneral
    - http://jpfhir.jp/fhir/eCheckup/StructureDefinition/JP_Media
    - http://jpfhir.jp/fhir/eCS/StructureDefinition/JP_Observation_Common_eCS
    - http://jpfhir.jp/fhir/eCheckup/StructureDefinition/JP_Observation_eCheckupGeneral
    - http://jpfhir.jp/fhir/eCheckup/StructureDefinition/JP_ObservationGroup_eCheckupGeneral
    - http://jpfhir.jp/fhir/eCS/StructureDefinition/JP_Organization_eCS_coveragePayer
    - http://jpfhir.jp/fhir/eCheckup/StructureDefinition/JP_Organization_eCheckupGeneral
    - http://jpfhir.jp/fhir/eCheckup/StructureDefinition/JP_OrganizationInsurer_eCheckupGeneral
    - http://jpfhir.jp/fhir/clins/StructureDefinition/JP_Patient_eCheckupGeneral
    - http://jpfhir.jp/fhir/eCheckup/StructureDefinition/JP_Practitioner_eCheckupGeneral
    - http://jpfhir.jp/fhir/eCheckup/StructureDefinition/JP_PractitionerRole_eCheckupGeneral
    - http://jpfhir.jp/fhir/eCS/StructureDefinition/JP_Procedure_eCS
    - http://jpfhir.jp/fhir/eCS/StructureDefinition/JP_RelatedPerson_eCS
    - http://jpfhir.jp/fhir/core/StructureDefinition/JP_RelatedPerson
    - http://jpfhir.jp/fhir/eCS/StructureDefinition/JP_ResearchStudy_eCS
    - http://jpfhir.jp/fhir/core/StructureDefinition/JP_ResearchStudy
    - http://jpfhir.jp/fhir/eCS/StructureDefinition/JP_ResearchSubject_eCS
    - http://jpfhir.jp/fhir/core/StructureDefinition/JP_ResearchSubject
    - http://jpfhir.jp/fhir/eCheckup/StructureDefinition/JP_Specimen_eCheckupGeneral
    - http://jpfhir.jp/fhir/eCheckup/Extension/StructureDefinition/JP_Age_At_Event
    - http://jpfhir.jp/fhir/eCheckup/Extension/StructureDefinition/JP_Checkup_Fee_Collection_Status
    - http://jpfhir.jp/fhir/Common/Extension/StructureDefinition/composition-clinicaldocument-versionNumber
    - http://jpfhir.jp/fhir/eCheckup/Extension/StructureDefinition/composition_dataEnterer
    - http://jpfhir.jp/fhir/eCS/Extension/StructureDefinition/JP_eCS_Department
    - http://jpfhir.jp/fhir/clins/Extension/StructureDefinition/JP_eCS_InstitutionNumber
    - http://jpfhir.jp/fhir/Common/Extension/StructureDefinition/observatioGroupRelationship
    - http://jpfhir.jp/fhir/eCheckup/CodeSystem/attachement-format
    - http://jpfhir.jp/fhir/eCheckup/CodeSystem/encounter-category
    - http://jpfhir.jp/fhir/eCheckup/CodeSystem/checkup-encounter-type
    - http://jpfhir.jp/fhir/eCheckup/CodeSystem/observationGroup-codes
    - http://jpfhir.jp/fhir/eCheckup/CodeSystem/observationGroupRelationship-codes
    - http://jpfhir.jp/fhir/eCheckup/CodeSystem/report-organization-code
    - http://jpfhir.jp/fhir/eCheckup/CodeSystem/checkup-report-category
    - http://jpfhir.jp/fhir/eCheckup/CodeSystem/checkup-programService-code
    - http://jpfhir.jp/fhir/eCheckup/CodeSystem/section-code
    - urn:oid:1.2.392.200119.6.208
    - urn:oid:1.2.392.200119.6.1002
    - http://jpfhir.jp/fhir/Common/CodeSystem/doc-typecodes
    - urn:oid:2.16.840.1.113883.2.2.1.6.1001
    - urn:oid:1.2.392.200119.6.1008
    - urn:oid:1.2.392.200119.6.18030
    - urn:oid:1.2.392.200119.6.18040
    - urn:oid:1.2.392.200119.6.18050
    - urn:oid:1.2.392.200119.6.18060
    - urn:oid:1.2.392.200119.6.18080
    - urn:oid:1.2.392.200119.6.18090
    - urn:oid:1.2.392.200119.6.18100
    - urn:oid:1.2.392.200119.6.18120
    - urn:oid:1.2.392.200119.6.18130
    - urn:oid:1.2.392.200119.6.19010
    - urn:oid:1.2.392.200119.6.19020
    - urn:oid:1.2.392.200119.6.19030
    - urn:oid:1.2.392.200119.6.19040
    - urn:oid:1.2.392.200119.6.19050
    - urn:oid:1.2.392.200119.6.19060
    - urn:oid:1.2.392.200119.6.19070
    - urn:oid:1.2.392.200119.6.19080
    - urn:oid:1.2.392.200119.6.19090
    - urn:oid:1.2.392.200119.6.19100
    - urn:oid:1.2.392.200119.6.19110
    - urn:oid:1.2.392.200119.6.19120
    - urn:oid:1.2.392.200119.6.19130
    - urn:oid:1.2.392.200119.6.19140
    - urn:oid:1.2.392.200119.6.19150
    - urn:oid:1.2.392.200119.6.2001
    - urn:oid:1.2.392.200119.6.2002
    - urn:oid:1.2.392.200119.6.2003
    - urn:oid:1.2.392.200119.6.2004
    - urn:oid:1.2.392.200119.6.2007
    - urn:oid:1.2.392.200119.6.2008
    - urn:oid:1.2.392.200119.6.2009
    - urn:oid:1.2.392.200119.6.2100
    - urn:oid:1.2.392.200119.6.2102
    - urn:oid:1.2.392.200119.6.2103
    - urn:oid:1.2.392.200119.6.2110
    - urn:oid:1.2.392.200119.6.2111
    - urn:oid:1.2.392.200119.6.2112
    - urn:oid:1.2.392.200119.6.2113
    - urn:oid:1.2.392.200119.6.2115
    - urn:oid:1.2.392.200119.6.2116
    - urn:oid:1.2.392.200119.6.2120
    - urn:oid:1.2.392.200119.6.2122
    - urn:oid:1.2.392.200119.6.2130
    - urn:oid:1.2.392.200119.6.2131
    - urn:oid:1.2.392.200119.6.2140
    - urn:oid:1.2.392.200119.6.2141
    - urn:oid:1.2.392.200119.6.2150
    - urn:oid:1.2.392.200119.6.2202
    - urn:oid:1.2.392.200119.6.2301
    - urn:oid:1.2.392.200119.6.24020
    - urn:oid:1.2.392.200119.6.24040
    - urn:oid:1.2.392.200119.6.24050
    - urn:oid:1.2.392.200119.6.24060
    - urn:oid:1.2.392.200119.6.24080
    - urn:oid:1.2.392.200119.6.2501
    - urn:oid:1.2.392.200119.6.2502
    - urn:oid:1.2.392.200119.6.3001
    - urn:oid:1.2.392.200119.6.1007
    - urn:oid:1.2.392.200119.6.1005
    - http://jpfhir.jp/fhir/eCheckup/ValueSet/encounter-category
    - http://jpfhir.jp/fhir/eCheckup/ValueSet/checkup-encounter-type
    - http://jpfhir.jp/fhir/eCheckup/ValueSet/report-organization-code
    - http://jpfhir.jp/fhir/eCheckup/ValueSet/observationGroup-codes
    - http://jpfhir.jp/fhir/eCheckup/ValueSet/observationGroupRelationship-codes
    - http://jpfhir.jp/fhir/eCheckup/ValueSet/section-code
    - http://jpfhir.jp/fhir/eCheckup/ValueSet/checkup-programService-code
    - http://jpfhir.jp/fhir/eCheckup/ValueSet/checkup-report-category
    - http://jpfhir.jp/fhir/Common/ValueSet/doc-typecodes
    - http://jpfhir.jp/fhir/eCheckup/ValueSet/observation-code
    - http://jpfhir.jp/fhir/eCheckup/ValueSet/mergedCheckup-report-category
    - http://jpfhir.jp/fhir/eCheckup/ValueSet/specialCheckup-report-category
