# ╭─────────────────────────Commonly Used ImplementationGuide Properties───────────────────────────╮
# │  The properties below are used to create the ImplementationGuide resource. The most commonly   │
# │  used properties are included. For a list of all supported properties and their functions,     │
# │  see: https://fshschool.org/docs/sushi/configuration/.                                  │
# ╰────────────────────────────────────────────────────────────────────────────────────────────────╯
id: eCheckupReport
canonical: http://jpfhir.jp/fhir/eCheckupReport
name: "健診結果報告FHIR実装ガイド"
title: "健診結果報告FHIR実装ガイド"
description: "健診結果報告FHIR実装ガイド eCheckupReport Implementation Guide"
status: draft # draft | active | retired | unknown
version: 1.1.1
fhirVersion: 4.0.1 # https://www.hl7.org/fhir/valueset-FHIR-version.html 
copyrightYear: 2023+
releaseLabel: draft # ci-build | draft | qa-preview | ballot | trial-use | release | update | normative+trial-use
# license: CC0-1.0 # https://www.hl7.org/fhir/valueset-spdx-license.html
# jurisdiction: urn:iso:std:iso:3166#US "United States of America" # https://www.hl7.org/fhir/valueset-jurisdiction.html
publisher:
  name: 大江和彦（東京大学医学部附属病院企画情報運営部）Kazuhiko Ohe@JAMI/HL7Japan, and The University of Tokyo
  url: http://jpfhir.jp
  email: office@hlfhir.jp
copyright: Copyright JAMI 
jurisdiction: 'urn:iso:std:iso:3166-2#JP'
dependencies:
  jp-core.r4:
    uri: http://jpfhir.jp/fhir/core/1.1.2/ImplementationGuide/
    version: 1.1.2
  jpfhir-terminology.r4:
    uri: http://jpfhir.jp/fhir//jpfhir-terminology.r4/ImplementationGuide/
    version: 1.1.1

#
#----------------------------------------
# ページタイトル名称設定
#----------------------------------------
pages:
  index.md:
    title: 健診結果報告書HL7&reg; FHIR&reg;記述仕様書 第1.1版
  tables.md:
    title: 各表一覧
  history.md:
    title: 改訂履歴
#-------------------------------------
# メニュー設定
#-------------------------------------
menu:
  Home:
    本文: index.html
    プロファイル: artifacts.html
    改訂履歴: history.html
  Artifacts: 
    Artifacts: artifacts.html

#-----------------------------------------
# IG 外部パラメータ設定
#-----------------------------------------
parameters:  # see https://confluence.hl7.org/display/FHIR/Implementation+Guide+Parameters
  path-resource:
    - input/resources
    - fsh-generated/resources
  path-pages:
    - input/pagecontent
    - input/intro-notes
    - fsh-generated/includes
    #- input/summaries
  path-expansion-params: '../../input/_resources/exp-params.json'
  no-narrative: 
    - CodeSystem/*
  active-tables: 'false'
  apply-version: 'true'
  apply-copyright: 'true'
  apply-publisher: 'true'
  apply-contact: 'true'
  apply-license: 'true'
  apply-jurisdiction: 'true'
  show-inherited-invariants: 'true'
  usage-stats-opt-out: 'true'
  display-warnings: 'true'
  excludexml: 'true'
  excludejson: 'false'
  excludettl: 'true'
  excludemap: 'true'
#  excludeexample: 'false'
  generate: #what does this do - todo: remove and see
    - json
  no-validate:
    - '*/hl7.fhir.jp.core'
  special-url:
    - http://jpfhir.jp/fhir/clins/StructureDefinition/JP_Bundle_eCheckupGeneral
    - http://jpfhir.jp/fhir/eCheckup/StructureDefinition/JP_Bundle_eCheckupGeneral
    - http://jpfhir.jp/fhir/eCheckup/StructureDefinition/JP_Composition_eCheckupGeneral
    - http://jpfhir.jp/fhir/eCheckup/StructureDefinition/JP_CoverageInsurance_eCheckupGeneral
    - http://jpfhir.jp/fhir/eCheckup/StructureDefinition/JP_CoverageService_eCheckupGeneral
    - http://jpfhir.jp/fhir/eCheckup/StructureDefinition/JP_DiagnosticReport_eCheckupGeneral
    - http://jpfhir.jp/fhir/eCheckup/StructureDefinition/JP_DocumentReference_eCheckupGeneral
    - http://jpfhir.jp/fhir/eCheckup/StructureDefinition/JP_Encounter_eCheckupGeneral
    - http://jpfhir.jp/fhir/eCheckup/StructureDefinition/JP_Media_eCheckupGeneral
    - http://jpfhir.jp/fhir/eCheckup/StructureDefinition/JP_Observation_eCheckupGeneral
    - http://jpfhir.jp/fhir/eCheckup/StructureDefinition/JP_ObservationGroup_eCheckupGeneral
    - http://jpfhir.jp/fhir/eCS/StructureDefinition/JP_Organization_eCS_coveragePayer
    - http://jpfhir.jp/fhir/eCS/StructureDefinition/JP_Organization_eClinicalSummary
    - http://jpfhir.jp/fhir/eCheckup/StructureDefinition/JP_Organization_eCheckupGeneral
    - http://jpfhir.jp/fhir/eCheckup/StructureDefinition/JP_OrganizationInsurer_eCheckupGeneral
    - http://jpfhir.jp/fhir/clins/StructureDefinition/JP_Patient_eCS
    - http://jpfhir.jp/fhir/eCS/StructureDefinition/JP_Patient_eCS
    - http://jpfhir.jp/fhir/eCheckup/StructureDefinition/JP_Practitioner_eCheckupGeneral
    - http://jpfhir.jp/fhir/eCheckup/StructureDefinition/JP_PractitionerRole_eCheckupGeneral
    - http://jpfhir.jp/fhir/eCheckup/StructureDefinition/JP_Specimen_eCheckupGeneral
    - http://jpfhir.jp/fhir/eCheckup/Extension/StructureDefinition/JP_Age_At_Event
    - http://jpfhir.jp/fhir/eCheckup/Extension/StructureDefinition/JP_Checkup_Fee_Collection_Status
    - http://jpfhir.jp/fhir/eCheckup/Extension/StructureDefinition/JP_Fiscal_Year_At_Primary_Checkup
    - http://hl7.org/fhir/StructureDefinition/composition-clinicaldocument-versionNumber
    - http://jpfhir.jp/fhir/eCheckup/Extension/StructureDefinition/composition_dataEnterer
    - http://jpfhir.jp/fhir/clins/Extension/StructureDefinition/JP_eCS_Department
    - http://jpfhir.jp/fhir/clins/Extension/StructureDefinition/JP_eCS_InstitutionNumber
    - http://jpfhir.jp/fhir/eCheckup/CodeSystem/attachement-format
    - http://jpfhir.jp/fhir/eCheckup/CodeSystem/encounter-category
    - http://jpfhir.jp/fhir/eCheckup/CodeSystem/jlac10-examMethod-codes
    - http://jpfhir.jp/fhir/eCheckup/CodeSystem/jlac10-specimen-codes
    - http://jpfhir.jp/fhir/eCheckup/CodeSystem/observationGroup-codes
    - http://jpfhir.jp/fhir/eCheckup/CodeSystem/checkup-report-category
    - http://jpfhir.jp/fhir/eCheckup/CodeSystem/section-code
    - urn:oid:1.2.392.200119.6.1002
    - http://jpfhir.jp/fhir/Common/CodeSystem/doc-typecodes
    - urn:oid:1.2.392.100495.20.3.21
    - urn:oid:1.2.392.100495.20.2.61
    - urn:oid:1.2.392.100495.20.2.63
    - urn:oid:1.2.392.100495.20.2.62
    - urn:oid:2.16.840.1.113883.2.2.1.6.1001
    - urn:oid:1.2.392.200119.6.1005
    - http://jpfhir.jp/fhir/eCheckup/ValueSet/section-code
    - http://jpfhir.jp/fhir/eCheckup/ValueSet/checkup-programService-code
    - http://jpfhir.jp/fhir/eCheckup/ValueSet/checkup-report-category
    - http://jpfhir.jp/fhir/Common/ValueSet/doc-typecodes
    - http://jpfhir.jp/fhir/eCheckup/ValueSet/observation-code
    - http://jpfhir.jp/fhir/Common/ValueSet/doc-typecodes
    - http://jpfhir.jp/fhir/eCheckup/ValueSet/mergedCheckup-report-category
    - http://jpfhir.jp/fhir/Common/ValueSet/mhlw-ePreCDA-insuredRelationship
    - http://jpfhir.jp/fhir/eCheckup/ValueSet/specialCheckup-report-category
   